language: go
install:
- make get-deps
script:
- make
deploy:
  provider: releases
  skip_cleanup: true
  file: distrib/linux/ccontainermain
  on:
    tags: true
  api_key:
    secure: RQ4bo6M+7yUy+y9Pbw+jgKQlAKEehL0s0o1sb/BSliVE+sQXBRPul8QZ/P2qOfCrR6KiVXs8NFB18R7rX/hUUGRxR3cNrjMazP56rehwPrXfT/ZhOCMM/2KK/A3CTZvS/EJebQabyU0O5uKFT0sVqh1Ylo/f4uldMpZVF0ekn0V4HrCeyAp381XC+aZRKuuoxpLkDrDduGbEY8gs5FHFQnlyJG3dJYrETYOPP0CQX26l2fP3xhiCIZGG/YxrGP27jwCUMkz5SIBuQKJU8PwbjRiaEmiXx1H/aJfMvPHT8nkj6g5T5OEmoj8h80XtotDda331jkvPgAyP/a7uAsRsxyDNqq5viMa16eRVS6rECtpMQa+bQ//djq3raJ0FKVJZrYR5YUlhSYJOTuByljYPtL88BLh2E0U7XfyUbBIa5zS8sqKVXnIeNF1VUKbgCU0wfXr2uCOgu2i0NkJ8BFNXQ1U87rMkm6uUDQiogQanPsqSMvpX0k2CPwZO2KpSvv/nQCX76Mfw17T2yzIMaSmbI0XAHRPcLQbq7KoSffITl7B6ndKRIU3stekKGqi6h3GlF0wqZvs3+i+MAYNUdGvLtINKcC7wOPrYEt8CrzCxh+dw9TZnWwCR93MJPfdzQJPP2Pnc1pgs7UzSZXCOyNJ0zyMTs+/mKtv6H4AMOnMIftE=
